-- MySQL Script generated by MySQL Workbench
-- 11/29/17 11:10:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `role` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `phoneNr` VARCHAR(45) NOT NULL COMMENT '',
  `cellphoneNr` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(1045) NULL COMMENT '',
  PRIMARY KEY (`customerID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `categoryID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`categoryID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Device` (
  `deviceID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `categoryID` INT NOT NULL COMMENT '',
  `deviceInfo` VARCHAR(45) NULL COMMENT '',
  `serialnr` INT NOT NULL COMMENT '',
  PRIMARY KEY (`deviceID`, `categoryID`)  COMMENT '',
  INDEX `fk_Apparaat_Categorie1_idx` (`categoryID` ASC)  COMMENT '',
  CONSTRAINT `fk_Apparaat_Categorie1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `mydb`.`Category` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reparation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reparation` (
  `repairID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `customerID` INT NOT NULL COMMENT '',
  `deviceID` INT NOT NULL COMMENT '',
  `statusID` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  `chargerIncluded` TINYINT(1) NOT NULL COMMENT '',
  `finished` TINYINT(1) NOT NULL COMMENT '',
  `checked` TINYINT(1) NOT NULL COMMENT '',
  `repairedBy` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`repairID`, `customerID`, `deviceID`, `repairedBy`)  COMMENT '',
  INDEX `fk_Reparatie_Apparaat1_idx` (`deviceID` ASC)  COMMENT '',
  INDEX `fk_Reparatie_Klant1_idx` (`customerID` ASC)  COMMENT '',
  INDEX `fk_Reparation_User1_idx` (`repairedBy` ASC)  COMMENT '',
  CONSTRAINT `fk_Reparatie_Apparaat1`
    FOREIGN KEY (`deviceID`)
    REFERENCES `mydb`.`Device` (`deviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparatie_Klant1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reparation_User1`
    FOREIGN KEY (`repairedBy`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
